// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240511090443_Avaliacoes")]
    partial class Avaliacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("API.Entities.Avaliacao", b =>
                {
                    b.Property<int>("OlheiroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EhFan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaGeral")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaGoleiro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaHabilidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaMarcacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaRaca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotaVelocidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("OlheiroId", "AvaliadoId");

                    b.HasIndex("AvaliadoId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("API.Entities.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alcunha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtivoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HashSenha")
                        .HasColumnType("BLOB");

                    b.Property<string>("Recado")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SalSenha")
                        .HasColumnType("BLOB");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("API.Entities.Avaliacao", b =>
                {
                    b.HasOne("API.Entities.Jogador", "Avaliado")
                        .WithMany("AvalRecebidas")
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Jogador", "Olheiro")
                        .WithMany("AvalFeitas")
                        .HasForeignKey("OlheiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliado");

                    b.Navigation("Olheiro");
                });

            modelBuilder.Entity("API.Entities.Jogador", b =>
                {
                    b.Navigation("AvalFeitas");

                    b.Navigation("AvalRecebidas");
                });
#pragma warning restore 612, 618
        }
    }
}
