# Generated by Django 5.2.1 on 2025-06-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='overall_rating',
            new_name='overall',
        ),
    ]
